import { CategoryType, Tool } from './types';

// Helper to generate placeholder images deterministically
// Using academic/tech themes
const getImg = (id: string | number, type: string) => `https://picsum.photos/seed/${id}${type}/300/200`;

export const ALL_TOOLS: Tool[] = [
  // --- 核心推荐 (Featured) ---
  {
    id: 'metaso',
    name: '秘塔 AI 搜索',
    description: '无广告的 AI 搜索，精准直达学术内容，深度整合全网信息。',
    url: 'https://metaso.cn/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['无广告', '学术搜索', '国产'],
    imageUrl: getImg('metaso', 'search'),
    isFeatured: true,
  },
  {
    id: 'xiezuocat',
    name: '秘塔写作猫',
    description: 'AI 辅助写作平台，支持长文生成、改写润色及纠错。',
    url: 'https://xiezuocat.com/',
    category: CategoryType.WRITING_ASSISTANT,
    tags: ['写作', '润色', '纠错'],
    imageUrl: getImg('xiezuocat', 'write'),
    isFeatured: true,
  },
  {
    id: 'nanoai',
    name: '纳米 AI (Nano)',
    description: '高效学术搜索与阅读助手，快速提炼核心观点，支持多模态。',
    url: 'https://www.n.cn/', 
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['阅读助手', '提效', '搜索'],
    imageUrl: getImg('nano', 'read'),
    isFeatured: true,
  },
  {
    id: 'jimeng',
    name: '即梦 AI',
    description: '字节跳动出品的图像生成与编辑工具，激发无限创意。',
    url: 'https://jimeng.jianying.com/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['绘图', '设计', '字节跳动'],
    imageUrl: getImg('jimeng', 'art'),
    isFeatured: true,
    isNew: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: '深度求索，国产开源大模型领跑者，擅长代码与深度逻辑推理。',
    url: 'https://www.deepseek.com/',
    category: CategoryType.CODING,
    tags: ['代码', '推理', '开源'],
    imageUrl: getImg('deepseek', 'code'),
    isFeatured: true,
  },
  {
    id: 'kimi',
    name: 'Kimi 智能助手',
    description: '超长上下文窗口，擅长阅读长篇文献与整理资料。',
    url: 'https://kimi.moonshot.cn/',
    category: CategoryType.GENERAL_AI,
    tags: ['长文本', '文献阅读', '助手'],
    imageUrl: getImg('kimi', 'chat'),
    isFeatured: true,
  },

  // --- 综合通用 AI (General AI) ---
  {
    id: 'tongyi',
    name: '通义千问',
    description: '阿里巴巴大模型，全能型 AI 助手，支持复杂文档解析。',
    url: 'https://tongyi.aliyun.com/',
    category: CategoryType.GENERAL_AI,
    tags: ['阿里', '文档解析', '全能'],
    imageUrl: getImg('tongyi', 'ali'),
  },
  {
    id: 'doubao',
    name: '豆包',
    description: '字节跳动旗下 AI 助手，语音交互体验优秀，适合日常查询。',
    url: 'https://www.doubao.com/',
    category: CategoryType.GENERAL_AI,
    tags: ['语音', '日常', '字节'],
    imageUrl: getImg('doubao', 'byte'),
  },
  {
    id: 'hunyuan',
    name: '腾讯混元',
    description: '腾讯全链路自研大模型，办公场景深度集成。',
    url: 'https://hunyuan.tencent.com/',
    category: CategoryType.GENERAL_AI,
    tags: ['腾讯', '办公', '协作'],
    imageUrl: getImg('hunyuan', 'tencent'),
  },
  {
    id: 'spark',
    name: '讯飞星火',
    description: '科大讯飞出品，强大的语音转写与多模态能力。',
    url: 'https://xinghuo.xfyun.cn/',
    category: CategoryType.GENERAL_AI,
    tags: ['语音', '写作', '教育'],
    imageUrl: getImg('spark', 'xfyun'),
  },
  {
    id: 'ernie',
    name: '文心一言',
    description: '百度出品的知识增强大语言模型，中文理解能力强。',
    url: 'https://yiyan.baidu.com/',
    category: CategoryType.GENERAL_AI,
    tags: ['百度', '中文', '知识'],
    imageUrl: getImg('ernie', 'baidu'),
  },
  {
    id: 'chatglm',
    name: '智谱清言',
    description: '基于 ChatGLM 模型，擅长中文问答与数据分析。',
    url: 'https://chatglm.cn/',
    category: CategoryType.GENERAL_AI,
    tags: ['清华系', '开源', '对话'],
    imageUrl: getImg('chatglm', 'tsinghua'),
  },
  {
    id: 'tiangong',
    name: '天工 AI',
    description: '昆仑万维出品，拥有强大的搜索与生成能力。',
    url: 'https://www.tiangong.cn/',
    category: CategoryType.GENERAL_AI,
    tags: ['搜索', '生成', '多模态'],
    imageUrl: getImg('tiangong', 'sky'),
  },
  {
    id: 'wanzhi',
    name: '万知',
    description: '零一万物出品，擅长文档阅读与PPT生成。',
    url: 'https://www.wanzhi.com/',
    category: CategoryType.GENERAL_AI,
    tags: ['PPT', '文档', '李开复'],
    imageUrl: getImg('wanzhi', '01'),
  },
  {
    id: 'zhinao',
    name: '360 智脑',
    description: '360 出品的认知型通用大模型，安全可靠。',
    url: 'https://ai.360.com/',
    category: CategoryType.GENERAL_AI,
    tags: ['安全', '办公', '360'],
    imageUrl: getImg('360', 'safe'),
  },
  {
    id: 'sensechat',
    name: '商量 SenseChat',
    description: '商汤科技大模型，擅长多轮对话与逻辑推理。',
    url: 'https://chat.sensetime.com/',
    category: CategoryType.GENERAL_AI,
    tags: ['商汤', '视觉', '推理'],
    imageUrl: getImg('sense', 'time'),
  },
  {
    id: 'hailuo',
    name: '海螺 AI',
    description: 'MiniMax 出品的通用人工智能助手。',
    url: 'https://www.hailuoai.com/',
    category: CategoryType.GENERAL_AI,
    tags: ['通用', '助手', 'MiniMax'],
    imageUrl: getImg('hailuo', 'shell'),
  },

  // --- 学术检索与阅读 (Academic Search) ---
  {
    id: 'cnki-ai',
    name: 'CNKI AI 学术助手',
    description: '知网官方 AI 工具，深耕中文学术资源分析。',
    url: 'https://ai.cnki.net/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['知网', '中文学术', '权威'],
    imageUrl: getImg('cnki', 'paper'),
  },
  {
    id: 'aminer',
    name: 'AMiner',
    description: '清华大学 AI 赋能的科技情报大数据挖掘平台。',
    url: 'https://www.aminer.cn/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['清华', '情报', '挖掘'],
    imageUrl: getImg('aminer', 'data'),
  },
  {
    id: 'readpaper',
    name: 'ReadPaper',
    description: '集成论文阅读、翻译、管理的一站式科研平台。',
    url: 'https://readpaper.com/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['阅读', '社区', '笔记'],
    imageUrl: getImg('readpaper', 'read'),
  },
  {
    id: 'xmol',
    name: 'X-MOL',
    description: '化学、材料、生物医药领域的专业学术平台。',
    url: 'https://www.x-mol.com/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['化学', '生物', '专业'],
    imageUrl: getImg('xmol', 'chem'),
  },
  {
    id: 'semantic',
    name: 'Semantic Scholar',
    description: '免费的 AI 驱动学术搜索引擎，智能提取论文关键信息。',
    url: 'https://www.semanticscholar.org/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['免费', '全球', '语义'],
    imageUrl: getImg('semantic', 'scholar'),
  },
  {
    id: 'connected',
    name: 'Connected Papers',
    description: '可视化的论文引用关系图谱，快速发现相关文献。',
    url: 'https://www.connectedpapers.com/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['图谱', '可视化', '关联'],
    imageUrl: getImg('connected', 'graph'),
  },
  {
    id: 'researchrabbit',
    name: 'ResearchRabbit',
    description: '像Spotify一样的文献推荐引擎，智能发现研究路径。',
    url: 'https://www.researchrabbit.ai/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['推荐', '发现', '路径'],
    imageUrl: getImg('rabbit', 'research'),
  },
  {
    id: 'scispace',
    name: 'SciSpace',
    description: '一站式论文阅读、解释与写作助手 (原Typeset)。',
    url: 'https://typeset.io/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['解释', '阅读', '助手'],
    imageUrl: getImg('scispace', 'space'),
  },
  {
    id: 'consensus',
    name: 'Consensus',
    description: '基于证据的 AI 搜索引擎，直接从论文中提取科学结论。',
    url: 'https://consensus.app/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['结论', '证据', '科学'],
    imageUrl: getImg('consensus', 'fact'),
  },
  {
    id: 'elicit',
    name: 'Elicit',
    description: 'AI 研究助手，自动化文献综述与数据提取。',
    url: 'https://elicit.com/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['综述', '提取', '自动化'],
    imageUrl: getImg('elicit', 'review'),
  },
  {
    id: 'scholarcy',
    name: 'Scholarcy',
    description: '在线论文摘要生成工具，快速提炼文献重点。',
    url: 'https://www.scholarcy.com/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['摘要', '速读', '闪卡'],
    imageUrl: getImg('scholarcy', 'card'),
  },
  {
    id: 'chatpdf',
    name: 'ChatPDF',
    description: '与 PDF 对话，快速提取文档内容与回答问题。',
    url: 'https://www.chatpdf.com/',
    category: CategoryType.ACADEMIC_SEARCH,
    tags: ['PDF', '对话', '文档'],
    imageUrl: getImg('chatpdf', 'pdf'),
  },

  // --- 论文写作与润色 (Writing) ---
  {
    id: 'biling',
    name: '笔灵 AI',
    description: '面向学生的论文写作与降重工具。',
    url: 'https://ibiling.cn/',
    category: CategoryType.WRITING_ASSISTANT,
    tags: ['学生', '写作', '降重'],
    imageUrl: getImg('biling', 'pen'),
  },
  {
    id: 'huolongguo',
    name: '火龙果写作',
    description: '跨平台智能写作工具，提供纠错、改写与润色功能。',
    url: 'https://www.mypitaya.com/',
    category: CategoryType.WRITING_ASSISTANT,
    tags: ['纠错', '润色', '多平台'],
    imageUrl: getImg('pitaya', 'fruit'),
  },
  {
    id: 'notion',
    name: 'Notion AI',
    description: '整合在笔记中的 AI，快速生成大纲与总结。',
    url: 'https://www.notion.so/',
    category: CategoryType.WRITING_ASSISTANT,
    tags: ['笔记', '大纲', '整理'],
    imageUrl: getImg('notion', 'note'),
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    description: '全球领先的英文写作纠错与润色助手。',
    url: 'https://www.grammarly.com/',
    category: CategoryType.WRITING_ASSISTANT,
    tags: ['英文', '纠错', '全球'],
    imageUrl: getImg('grammarly', 'abc'),
  },
  {
    id: 'quillbot',
    name: 'QuillBot',
    description: '强大的英文改写与同义词替换工具。',
    url: 'https://quillbot.com/',
    category: CategoryType.WRITING_ASSISTANT,
    tags: ['改写', '同义词', '降重'],
    imageUrl: getImg('quillbot', 'quill'),
  },
  {
    id: 'paperpal',
    name: 'PaperPal',
    description: '专为学术写作设计的 AI 编辑，提供语言建议。',
    url: 'https://paperpal.com/',
    category: CategoryType.WRITING_ASSISTANT,
    tags: ['学术', '编辑', '出版'],
    imageUrl: getImg('paperpal', 'pal'),
  },
  {
    id: 'wordtune',
    name: 'Wordtune',
    description: '智能语句重写工具，让表达更地道。',
    url: 'https://www.wordtune.com/',
    category: CategoryType.WRITING_ASSISTANT,
    tags: ['重写', '表达', '地道'],
    imageUrl: getImg('wordtune', 'tune'),
  },
  {
    id: 'hix',
    name: 'HIX.AI',
    description: '一站式 AI 写作助手，涵盖多种写作场景。',
    url: 'https://hix.ai/',
    category: CategoryType.WRITING_ASSISTANT,
    tags: ['全能', '写作', '助手'],
    imageUrl: getImg('hix', 'ai'),
  },

  // --- 翻译润色 (Translation) ---
  {
    id: 'deepl',
    name: 'DeepL',
    description: '公认翻译质量最高的 AI 翻译工具之一。',
    url: 'https://www.deepl.com/',
    category: CategoryType.TRANSLATION,
    tags: ['精准', '翻译', '德企'],
    imageUrl: getImg('deepl', 'translate'),
  },
  {
    id: 'immersive',
    name: '沉浸式翻译',
    description: '浏览器插件，提供双语对照网页翻译体验。',
    url: 'https://immersivetranslate.com/',
    category: CategoryType.TRANSLATION,
    tags: ['插件', '双语', '网页'],
    imageUrl: getImg('immersive', 'web'),
  },
  {
    id: 'transmart',
    name: '腾讯交互翻译',
    description: '腾讯 AI Lab 出品的交互式辅助翻译工具。',
    url: 'https://transmart.qq.com/',
    category: CategoryType.TRANSLATION,
    tags: ['腾讯', '交互', '辅助'],
    imageUrl: getImg('transmart', 'qq'),
  },

  // --- 编程辅助 (Coding) ---
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: '最流行的 AI 编程助手，实时代码补全。',
    url: 'https://github.com/features/copilot',
    category: CategoryType.CODING,
    tags: ['补全', '微软', '主流'],
    imageUrl: getImg('copilot', 'git'),
  },
  {
    id: 'codegeex',
    name: 'CodeGeeX',
    description: '智谱 AI 推出的多语言代码生成模型。',
    url: 'https://codegeex.cn/',
    category: CategoryType.CODING,
    tags: ['国产', '生成', '插件'],
    imageUrl: getImg('codegeex', 'geex'),
  },
  {
    id: 'marscode',
    name: 'MarsCode',
    description: '豆包旗下的 AI 编程助手，提供智能补全与解释。',
    url: 'https://www.marscode.cn/',
    category: CategoryType.CODING,
    tags: ['字节', 'IDE', '补全'],
    imageUrl: getImg('mars', 'code'),
  },
  {
    id: 'comate',
    name: '百度 Comate',
    description: '百度出品的智能编码助手，支持多种 IDE。',
    url: 'https://comate.baidu.com/',
    category: CategoryType.CODING,
    tags: ['百度', '企业级', '编码'],
    imageUrl: getImg('comate', 'baidu'),
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: '集成了 AI 的新一代代码编辑器。',
    url: 'https://cursor.sh/',
    category: CategoryType.CODING,
    tags: ['编辑器', '集成', '创新'],
    imageUrl: getImg('cursor', 'ide'),
  },
  {
    id: 'lingma',
    name: '通义灵码',
    description: '阿里云出品的智能编码助手。',
    url: 'https://tongyi.aliyun.com/lingma',
    category: CategoryType.CODING,
    tags: ['阿里', '插件', '免费'],
    imageUrl: getImg('lingma', 'ali'),
  },

  // --- 图像与视频 (Image & Video) ---
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: '艺术级图像生成工具，适合论文插图与封面设计。',
    url: 'https://www.midjourney.com/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['艺术', '绘图', '设计'],
    imageUrl: getImg('mj', 'paint'),
  },
  {
    id: 'stablediffusion',
    name: 'Stable Diffusion',
    description: '开源的图像生成模型，可本地部署。',
    url: 'https://stability.ai/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['开源', '本地', '控制'],
    imageUrl: getImg('sd', 'stable'),
  },
  {
    id: 'liblib',
    name: 'LiblibAI',
    description: '国内领先的 AI 绘画模型分享与在线生成社区。',
    url: 'https://www.liblib.art/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['社区', '模型', '国产'],
    imageUrl: getImg('liblib', 'art'),
  },
  {
    id: 'duiyou',
    name: '堆友',
    description: '阿里推出的 3D 风格 AI 设计工具。',
    url: 'https://d.design/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['3D', '设计', '阿里'],
    imageUrl: getImg('duiyou', '3d'),
  },
  {
    id: 'wujie',
    name: '无界 AI',
    description: '专注于二次元与艺术风格的国产绘画工具。',
    url: 'https://www.wujieai.com/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['二次元', '艺术', '创作'],
    imageUrl: getImg('wujie', 'draw'),
  },
  {
    id: 'kling',
    name: '可灵 AI',
    description: '快手出品的高质量视频生成模型。',
    url: 'https://kling.kuaishou.com/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['视频', '快手', '真实'],
    imageUrl: getImg('kling', 'video'),
  },
  {
    id: 'vidu',
    name: 'Vidu',
    description: '生数科技出品的长时长视频生成模型。',
    url: 'https://www.vidu.studio/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['视频', '清华系', '生成'],
    imageUrl: getImg('vidu', 'movie'),
  },
  {
    id: 'runway',
    name: 'Runway',
    description: '国际领先的 AI 视频编辑与生成平台。',
    url: 'https://runwayml.com/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['视频', '编辑', '创意'],
    imageUrl: getImg('runway', 'film'),
  },

  // --- 数据分析与办公 (Data & Office) ---
  {
    id: 'wpsai',
    name: 'WPS AI',
    description: '金山办公推出的智能办公助手，集成于文档/表格/PPT。',
    url: 'https://ai.wps.cn/',
    category: CategoryType.GENERAL_AI,
    tags: ['办公', '文档', '国产'],
    imageUrl: getImg('wps', 'office'),
  },
  {
    id: 'feishu',
    name: '飞书智能伙伴',
    description: '飞书办公套件中的 AI 助手。',
    url: 'https://www.feishu.cn/',
    category: CategoryType.GENERAL_AI,
    tags: ['协作', '会议', '总结'],
    imageUrl: getImg('feishu', 'lark'),
  },
  {
    id: 'gamma',
    name: 'Gamma',
    description: '新一代 AI 演示文稿生成工具，快速制作 PPT。',
    url: 'https://gamma.app/',
    category: CategoryType.WRITING_ASSISTANT, // Fits in assistant/productivity
    tags: ['PPT', '演示', '设计'],
    imageUrl: getImg('gamma', 'ppt'),
  },
  {
    id: 'chatppt',
    name: 'ChatPPT',
    description: '必优科技出品的 AI 生成 PPT 插件。',
    url: 'https://chat-ppt.com/',
    category: CategoryType.GENERAL_AI,
    tags: ['PPT', '插件', '效率'],
    imageUrl: getImg('chatppt', 'slide'),
  },
  {
    id: 'chatexcel',
    name: 'ChatExcel',
    description: '通过对话即可处理 Excel 表格数据的工具。',
    url: 'https://chatexcel.com/',
    category: CategoryType.DATA_ANALYSIS,
    tags: ['表格', '数据', '对话'],
    imageUrl: getImg('excel', 'sheet'),
  },
  {
    id: 'julius',
    name: 'Julius AI',
    description: '强大的数据分析助手，支持上传文件进行分析。',
    url: 'https://julius.ai/',
    category: CategoryType.DATA_ANALYSIS,
    tags: ['分析', '统计', '可视化'],
    imageUrl: getImg('julius', 'chart'),
  },
  {
    id: 'wolfram',
    name: 'Wolfram Alpha',
    description: '计算知识引擎，擅长数学、物理等科学计算。',
    url: 'https://www.wolframalpha.com/',
    category: CategoryType.DATA_ANALYSIS,
    tags: ['数学', '计算', '科学'],
    imageUrl: getImg('wolfram', 'math'),
  },
  
  // --- 创意与设计 (Design & Audio) ---
  {
    id: 'suno',
    name: 'Suno',
    description: '强大的 AI 音乐生成平台，可生成人声歌曲。',
    url: 'https://suno.com/',
    category: CategoryType.IMAGE_GENERATION, // Grouping under creation
    tags: ['音乐', '歌曲', '音频'],
    imageUrl: getImg('suno', 'music'),
  },
  {
    id: 'skymusic',
    name: '天工 SkyMusic',
    description: '昆仑万维推出的中文 AI 音乐生成 SOTA 模型。',
    url: 'https://music.tiangong.cn/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['音乐', '中文', '昆仑'],
    imageUrl: getImg('sky', 'song'),
  },
  {
    id: 'logoai',
    name: 'LogoAI',
    description: '智能 Logo 设计工具，快速生成品牌标识。',
    url: 'https://www.logoai.com/',
    category: CategoryType.IMAGE_GENERATION,
    tags: ['Logo', '品牌', '设计'],
    imageUrl: getImg('logo', 'brand'),
  }
];
